name: Trying for different shell

on:
   pull_request
      
jobs:
   run_windows_command:
      runs-on: windows-latest
      steps:
         - name: powershell command
           run: Get-Location
           shell: powershell
           
   run_command:
      runs-on: ubuntu-latest
      steps:
         - name: linux command
           id: linux
           run: pwd
         - name: python command
           run: |
              import platform
              print(platform.processor())
           shell: python
         - name: checkout
           uses: actions/checkout@v1
         - name: clone checkout actions
           run: |
              pwd
              ls
         
       
       
           
           
   
